project_id = "nagusztrqnacvkjaommv"

[functions]
  [functions.ai-persona-assist]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.notify-new-lead]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
